import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LANGUAGES_DIR = ROOT / "languages"

COMMON_DIRS = [
    "algorithms",
    "benchmarks",
    "compiler",
    "database",
    "documentation",
    "examples",
    "filesystem",
    "history",
    "json",
    "networking",
    "tests",
    "threads",
    "toolchain",
    "web",
    "xml",
]

LANGUAGES = [
    {
        "slug": "ada",
        "name": "Ada",
        "year": 1980,
        "paradigm": ["structured", "imperative", "concurrent"],
        "typing": "static",
        "runtime": "gnatmake",
        "extension": "adb",
        "filename": "main.adb",
        "example": 'with Ada.Text_IO; use Ada.Text_IO;\nprocedure Main is\nbegin\n   Put_Line("Hello, Omniforge from Ada!");\nend Main;\n',
    },
    {
        "slug": "awk",
        "name": "Awk",
        "year": 1977,
        "paradigm": ["text-processing", "scripting"],
        "typing": "dynamic",
        "runtime": "awk",
        "extension": "awk",
        "filename": "main.awk",
        "example": 'BEGIN { print "Hello, Omniforge from Awk!" }\n',
    },
    {
        "slug": "bash",
        "name": "Bash",
        "year": 1989,
        "paradigm": ["shell", "scripting"],
        "typing": "dynamic",
        "runtime": "bash",
        "extension": "sh",
        "filename": "main.sh",
        "example": 'printf "Hello, Omniforge from Bash!\\n"\n',
    },
    {
        "slug": "clojure",
        "name": "Clojure",
        "year": 2007,
        "paradigm": ["functional", "lisp", "jvm"],
        "typing": "dynamic",
        "runtime": "clojure",
        "extension": "clj",
        "filename": "main.clj",
        "example": '(println "Hello, Omniforge from Clojure!")\n',
    },
    {
        "slug": "cobol",
        "name": "COBOL",
        "year": 1959,
        "paradigm": ["procedural", "business"],
        "typing": "static",
        "runtime": "cobc",
        "extension": "cob",
        "filename": "main.cob",
        "example": '       IDENTIFICATION DIVISION.\n       PROGRAM-ID. MAIN.\n       PROCEDURE DIVISION.\n           DISPLAY "Hello, Omniforge from COBOL!".\n           STOP RUN.\n',
    },
    {
        "slug": "common-lisp",
        "name": "Common Lisp",
        "year": 1984,
        "paradigm": ["functional", "lisp", "multi-paradigm"],
        "typing": "dynamic",
        "runtime": "sbcl",
        "extension": "lisp",
        "filename": "main.lisp",
        "example": '(format t "Hello, Omniforge from Common Lisp!~%")\n',
    },
    {
        "slug": "crystal",
        "name": "Crystal",
        "year": 2014,
        "paradigm": ["compiled", "oop"],
        "typing": "static",
        "runtime": "crystal",
        "extension": "cr",
        "filename": "main.cr",
        "example": 'puts "Hello, Omniforge from Crystal!"\n',
    },
    {
        "slug": "d",
        "name": "D",
        "year": 2001,
        "paradigm": ["systems", "multi-paradigm"],
        "typing": "static",
        "runtime": "dmd",
        "extension": "d",
        "filename": "main.d",
        "example": 'import std.stdio;\nvoid main() {\n    writeln("Hello, Omniforge from D!");\n}\n',
    },
    {
        "slug": "dart",
        "name": "Dart",
        "year": 2011,
        "paradigm": ["oop", "client", "server"],
        "typing": "static",
        "runtime": "dart",
        "extension": "dart",
        "filename": "main.dart",
        "example": 'void main() {\n  print("Hello, Omniforge from Dart!");\n}\n',
    },
    {
        "slug": "elixir",
        "name": "Elixir",
        "year": 2012,
        "paradigm": ["functional", "concurrent", "beam"],
        "typing": "dynamic",
        "runtime": "elixir",
        "extension": "exs",
        "filename": "main.exs",
        "example": 'IO.puts("Hello, Omniforge from Elixir!")\n',
    },
    {
        "slug": "elm",
        "name": "Elm",
        "year": 2012,
        "paradigm": ["functional", "frontend"],
        "typing": "static",
        "runtime": "elm",
        "extension": "elm",
        "filename": "Main.elm",
        "example": 'module Main exposing (main)\n\nimport Html exposing (text)\n\nmain =\n    text "Hello, Omniforge from Elm!"\n',
    },
    {
        "slug": "erlang",
        "name": "Erlang",
        "year": 1986,
        "paradigm": ["functional", "concurrent", "beam"],
        "typing": "dynamic",
        "runtime": "escript",
        "extension": "erl",
        "filename": "main.erl",
        "example": '-module(main).\n-export([main/1]).\nmain(_) -> io:format("Hello, Omniforge from Erlang!~n").\n',
    },
    {
        "slug": "fortran",
        "name": "Fortran",
        "year": 1957,
        "paradigm": ["procedural", "numeric"],
        "typing": "static",
        "runtime": "gfortran",
        "extension": "f90",
        "filename": "main.f90",
        "example": 'program main\n  print *, "Hello, Omniforge from Fortran!"\nend program main\n',
    },
    {
        "slug": "forth",
        "name": "Forth",
        "year": 1970,
        "paradigm": ["stack-based", "concatenative"],
        "typing": "dynamic",
        "runtime": "gforth",
        "extension": "fs",
        "filename": "main.fs",
        "example": '.\\" Hello, Omniforge from Forth!" cr bye\n',
    },
    {
        "slug": "gleam",
        "name": "Gleam",
        "year": 2022,
        "paradigm": ["functional", "typed", "beam"],
        "typing": "static",
        "runtime": "gleam",
        "extension": "gleam",
        "filename": "main.gleam",
        "example": 'pub fn main() {\n  io.println("Hello, Omniforge from Gleam!")\n}\n',
    },
    {
        "slug": "groovy",
        "name": "Groovy",
        "year": 2003,
        "paradigm": ["dynamic", "jvm"],
        "typing": "dynamic",
        "runtime": "groovy",
        "extension": "groovy",
        "filename": "main.groovy",
        "example": 'println "Hello, Omniforge from Groovy!"\n',
    },
    {
        "slug": "haskell",
        "name": "Haskell",
        "year": 1990,
        "paradigm": ["functional", "lazy"],
        "typing": "static",
        "runtime": "runghc",
        "extension": "hs",
        "filename": "Main.hs",
        "example": 'main :: IO ()\nmain = putStrLn "Hello, Omniforge from Haskell!"\n',
    },
    {
        "slug": "janet",
        "name": "Janet",
        "year": 2017,
        "paradigm": ["lisp", "scripting"],
        "typing": "dynamic",
        "runtime": "janet",
        "extension": "janet",
        "filename": "main.janet",
        "example": '(print "Hello, Omniforge from Janet!")\n',
    },
    {
        "slug": "julia",
        "name": "Julia",
        "year": 2012,
        "paradigm": ["numeric", "scientific", "multiple-dispatch"],
        "typing": "dynamic",
        "runtime": "julia",
        "extension": "jl",
        "filename": "main.jl",
        "example": 'println("Hello, Omniforge from Julia!")\n',
    },
    {
        "slug": "kotlin",
        "name": "Kotlin",
        "year": 2011,
        "paradigm": ["multi-paradigm", "jvm"],
        "typing": "static",
        "runtime": "kotlinc",
        "extension": "kt",
        "filename": "Main.kt",
        "example": 'fun main() {\n    println("Hello, Omniforge from Kotlin!")\n}\n',
    },
    {
        "slug": "nim",
        "name": "Nim",
        "year": 2008,
        "paradigm": ["compiled", "metaprogramming"],
        "typing": "static",
        "runtime": "nim",
        "extension": "nim",
        "filename": "main.nim",
        "example": 'echo "Hello, Omniforge from Nim!"\n',
    },
    {
        "slug": "nushell",
        "name": "Nushell",
        "year": 2019,
        "paradigm": ["shell", "structured-data"],
        "typing": "dynamic",
        "runtime": "nu",
        "extension": "nu",
        "filename": "main.nu",
        "example": 'print "Hello, Omniforge from Nushell!"\n',
    },
    {
        "slug": "objective-c",
        "name": "Objective-C",
        "year": 1984,
        "paradigm": ["oop", "systems"],
        "typing": "static",
        "runtime": "clang",
        "extension": "m",
        "filename": "main.m",
        "example": '#import <stdio.h>\nint main(void) {\n    printf("Hello, Omniforge from Objective-C!\\n");\n    return 0;\n}\n',
    },
    {
        "slug": "ocaml",
        "name": "OCaml",
        "year": 1996,
        "paradigm": ["functional", "module-system"],
        "typing": "static",
        "runtime": "ocaml",
        "extension": "ml",
        "filename": "main.ml",
        "example": 'print_endline "Hello, Omniforge from OCaml!"\n',
    },
    {
        "slug": "octave",
        "name": "GNU Octave",
        "year": 1988,
        "paradigm": ["numeric", "matrix"],
        "typing": "dynamic",
        "runtime": "octave",
        "extension": "m",
        "filename": "main.m",
        "example": 'disp("Hello, Omniforge from Octave!")\n',
    },
    {
        "slug": "odin",
        "name": "Odin",
        "year": 2016,
        "paradigm": ["systems", "data-oriented"],
        "typing": "static",
        "runtime": "odin",
        "extension": "odin",
        "filename": "main.odin",
        "example": 'package main\n\nimport "core:fmt"\n\nmain :: proc() {\n    fmt.println("Hello, Omniforge from Odin!")\n}\n',
    },
    {
        "slug": "pascal",
        "name": "Pascal",
        "year": 1970,
        "paradigm": ["structured", "procedural"],
        "typing": "static",
        "runtime": "fpc",
        "extension": "pas",
        "filename": "main.pas",
        "example": 'program Main;\nbegin\n  writeln(\'Hello, Omniforge from Pascal!\');\nend.\n',
    },
    {
        "slug": "perl",
        "name": "Perl",
        "year": 1987,
        "paradigm": ["scripting", "text-processing"],
        "typing": "dynamic",
        "runtime": "perl",
        "extension": "pl",
        "filename": "main.pl",
        "example": 'print "Hello, Omniforge from Perl!\\n";\n',
    },
    {
        "slug": "php",
        "name": "PHP",
        "year": 1995,
        "paradigm": ["server-side", "scripting"],
        "typing": "dynamic",
        "runtime": "php",
        "extension": "php",
        "filename": "main.php",
        "example": '<?php\necho "Hello, Omniforge from PHP!\\n";\n',
    },
    {
        "slug": "prolog",
        "name": "Prolog",
        "year": 1972,
        "paradigm": ["logic"],
        "typing": "dynamic",
        "runtime": "swipl",
        "extension": "pl",
        "filename": "main.pl",
        "example": ':- initialization(main).\nmain :- writeln(\'Hello, Omniforge from Prolog!\').\n',
    },
    {
        "slug": "r",
        "name": "R",
        "year": 1993,
        "paradigm": ["statistical", "scripting"],
        "typing": "dynamic",
        "runtime": "Rscript",
        "extension": "R",
        "filename": "main.R",
        "example": 'cat("Hello, Omniforge from R!\\n")\n',
    },
    {
        "slug": "racket",
        "name": "Racket",
        "year": 1995,
        "paradigm": ["lisp", "language-oriented"],
        "typing": "dynamic",
        "runtime": "racket",
        "extension": "rkt",
        "filename": "main.rkt",
        "example": '#lang racket\n(displayln "Hello, Omniforge from Racket!")\n',
    },
    {
        "slug": "raku",
        "name": "Raku",
        "year": 2015,
        "paradigm": ["multi-paradigm", "scripting"],
        "typing": "gradual",
        "runtime": "raku",
        "extension": "raku",
        "filename": "main.raku",
        "example": 'say "Hello, Omniforge from Raku!";\n',
    },
    {
        "slug": "scheme",
        "name": "Scheme",
        "year": 1975,
        "paradigm": ["functional", "lisp"],
        "typing": "dynamic",
        "runtime": "racket",
        "extension": "scm",
        "filename": "main.scm",
        "example": '(displayln "Hello, Omniforge from Scheme!")\n',
    },
    {
        "slug": "smalltalk",
        "name": "Smalltalk",
        "year": 1972,
        "paradigm": ["oop", "reflective"],
        "typing": "dynamic",
        "runtime": "gst",
        "extension": "st",
        "filename": "main.st",
        "example": 'Transcript show: \'Hello, Omniforge from Smalltalk!\'; cr.\n',
    },
    {
        "slug": "swift",
        "name": "Swift",
        "year": 2014,
        "paradigm": ["protocol-oriented", "multi-paradigm"],
        "typing": "static",
        "runtime": "swift",
        "extension": "swift",
        "filename": "main.swift",
        "example": 'print("Hello, Omniforge from Swift!")\n',
    },
    {
        "slug": "tcl",
        "name": "Tcl",
        "year": 1988,
        "paradigm": ["scripting", "embeddable"],
        "typing": "dynamic",
        "runtime": "tclsh",
        "extension": "tcl",
        "filename": "main.tcl",
        "example": 'puts "Hello, Omniforge from Tcl!"\n',
    },
    {
        "slug": "typescript",
        "name": "TypeScript",
        "year": 2012,
        "paradigm": ["typed", "javascript"],
        "typing": "static",
        "runtime": "ts-node",
        "extension": "ts",
        "filename": "main.ts",
        "example": 'console.log("Hello, Omniforge from TypeScript!");\n',
    },
    {
        "slug": "vb",
        "name": "Visual Basic .NET",
        "year": 2001,
        "paradigm": ["event-driven", "oop"],
        "typing": "static",
        "runtime": "dotnet",
        "extension": "vb",
        "filename": "Main.vb",
        "example": 'Module Program\n    Sub Main(args As String())\n        System.Console.WriteLine("Hello, Omniforge from VB.NET!")\n    End Sub\nEnd Module\n',
    },
    {
        "slug": "webassembly",
        "name": "WebAssembly",
        "year": 2017,
        "paradigm": ["portable-binary", "vm-target"],
        "typing": "typed-binary",
        "runtime": "wasmtime",
        "extension": "wat",
        "filename": "main.wat",
        "example": '(module\n  (import "env" "log" (func $log))\n  (func (export "main") call $log)\n)\n',
    },
    {
        "slug": "zig",
        "name": "Zig",
        "year": 2016,
        "paradigm": ["systems", "compiled"],
        "typing": "static",
        "runtime": "zig",
        "extension": "zig",
        "filename": "main.zig",
        "example": 'const std = @import("std");\npub fn main() !void {\n    try std.io.getStdOut().writer().print("Hello, Omniforge from Zig!\\n", .{});\n}\n',
    },
    {
        "slug": "fennel",
        "name": "Fennel",
        "year": 2016,
        "paradigm": ["lisp", "lua"],
        "typing": "dynamic",
        "runtime": "fennel",
        "extension": "fnl",
        "filename": "main.fnl",
        "example": '(print "Hello, Omniforge from Fennel!")\n',
    },
    {
        "slug": "io",
        "name": "Io",
        "year": 2002,
        "paradigm": ["prototype-based", "dynamic"],
        "typing": "dynamic",
        "runtime": "io",
        "extension": "io",
        "filename": "main.io",
        "example": '"Hello, Omniforge from Io!" println\n',
    },
    {
        "slug": "idris",
        "name": "Idris",
        "year": 2011,
        "paradigm": ["functional", "dependent-types"],
        "typing": "static",
        "runtime": "idris2",
        "extension": "idr",
        "filename": "Main.idr",
        "example": 'module Main\n\nmain : IO ()\nmain = putStrLn "Hello, Omniforge from Idris!"\n',
    },
    {
        "slug": "agda",
        "name": "Agda",
        "year": 2007,
        "paradigm": ["functional", "dependent-types"],
        "typing": "static",
        "runtime": "agda",
        "extension": "agda",
        "filename": "Main.agda",
        "example": 'module Main where\n\nopen import IO\n\nmain = putStrLn "Hello, Omniforge from Agda!"\n',
    },
    {
        "slug": "purescript",
        "name": "PureScript",
        "year": 2013,
        "paradigm": ["functional", "typed", "javascript"],
        "typing": "static",
        "runtime": "purs",
        "extension": "purs",
        "filename": "Main.purs",
        "example": 'module Main where\n\nimport Prelude\n\nmain = unit\n',
    },
    {
        "slug": "elmish",
        "name": "Elmish",
        "year": 2016,
        "paradigm": ["functional", "ui-architecture"],
        "typing": "static",
        "runtime": "dotnet",
        "extension": "fs",
        "filename": "Program.fs",
        "example": 'printfn "Hello, Omniforge from Elmish!"\n',
    },
    {
        "slug": "hy",
        "name": "Hy",
        "year": 2013,
        "paradigm": ["lisp", "python"],
        "typing": "dynamic",
        "runtime": "hy",
        "extension": "hy",
        "filename": "main.hy",
        "example": '(print "Hello, Omniforge from Hy!")\n',
    },
    {
        "slug": "janus",
        "name": "Janus",
        "year": 1978,
        "paradigm": ["concurrent", "logic"],
        "typing": "dynamic",
        "runtime": "janus",
        "extension": "janus",
        "filename": "main.janus",
        "example": 'print("Hello, Omniforge from Janus")\n',
    },
    {
        "slug": "lfe",
        "name": "LFE",
        "year": 2008,
        "paradigm": ["lisp", "beam"],
        "typing": "dynamic",
        "runtime": "lfe",
        "extension": "lfe",
        "filename": "main.lfe",
        "example": '(io:format "Hello, Omniforge from LFE!~n" \'())\n',
    },
    {
        "slug": "logtalk",
        "name": "Logtalk",
        "year": 1998,
        "paradigm": ["logic", "oop"],
        "typing": "dynamic",
        "runtime": "logtalk",
        "extension": "lgt",
        "filename": "main.lgt",
        "example": ':- initialization(main).\nmain :- write(\'Hello, Omniforge from Logtalk!\'), nl.\n',
    },
    {
        "slug": "mercury",
        "name": "Mercury",
        "year": 1995,
        "paradigm": ["logic", "functional"],
        "typing": "static",
        "runtime": "mmc",
        "extension": "m",
        "filename": "main.m",
        "example": ':- module main.\n:- interface.\n:- import_module io.\n:- pred main(io::di, io::uo) is det.\n:- implementation.\nmain(!IO) :- io.write_string("Hello, Omniforge from Mercury!\\n", !IO).\n',
    },
    {
        "slug": "sml",
        "name": "Standard ML",
        "year": 1983,
        "paradigm": ["functional", "ml-family"],
        "typing": "static",
        "runtime": "sml",
        "extension": "sml",
        "filename": "main.sml",
        "example": 'print "Hello, Omniforge from Standard ML!\\n";\n',
    },
    {
        "slug": "v",
        "name": "V",
        "year": 2019,
        "paradigm": ["compiled", "systems"],
        "typing": "static",
        "runtime": "v",
        "extension": "v",
        "filename": "main.v",
        "example": 'fn main() {\n    println("Hello, Omniforge from V!")\n}\n',
    },
    {
        "slug": "vala",
        "name": "Vala",
        "year": 2006,
        "paradigm": ["oop", "gnome"],
        "typing": "static",
        "runtime": "valac",
        "extension": "vala",
        "filename": "main.vala",
        "example": 'void main() {\n    print("Hello, Omniforge from Vala!\\n");\n}\n',
    },
]


def main() -> None:
    created = []
    for language in LANGUAGES:
        slug = language["slug"]
        root = LANGUAGES_DIR / slug
        if root.exists():
            continue
        for dirname in COMMON_DIRS:
            (root / dirname).mkdir(parents=True, exist_ok=True)
        example_dir = root / "examples" / "hello-world"
        example_dir.mkdir(parents=True, exist_ok=True)
        (example_dir / language["filename"]).write_text(language["example"], encoding="utf-8")

        metadata = {
            "language": slug,
            "name": language["name"],
            "year": language["year"],
            "typing": language["typing"],
            "paradigm": language["paradigm"],
            "supportTier": "tier-0",
            "status": "catalogued",
            "workerStatus": "not-counted",
            "admissionRule": "Catalogued only until Omniforge has a detected runtime, OFP worker, verified coordinator path, and tests.",
        }
        (root / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")

        manifest = {
            "language": slug,
            "runtime": language["runtime"],
            "version": "unverified",
            "installStrategy": "detect-first",
            "hostSupport": ["windows"],
            "cataloguedOnly": True,
            "healthcheck": f"{language['runtime']} --version",
            "runExample": f"{language['runtime']} examples/hello-world/{language['filename']}",
        }
        (root / "toolchain" / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

        readme = f"""# {language['name']}

This language is catalogued in Omniforge but is not counted as a supported worker yet.

## Status

- Support tier: `Tier 0`
- Runtime: `{language['runtime']}`
- Worker status: `not counted`
- Admission rule: detected runtime, OFP worker, verified coordinator execution path, and automated tests

## Example

- [hello-world/{language['filename']}](examples/hello-world/{language['filename']})

## Notes

This directory exists so the language backlog is represented in-repo with concrete metadata and example code instead of only being mentioned in planning documents.
"""
        (root / "README.md").write_text(readme, encoding="utf-8")
        created.append(slug)

    print(json.dumps({"created": created, "count": len(created)}, indent=2))


if __name__ == "__main__":
    main()
